/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-aarch64"
#define DATE "built on: Tue Jan 16 12:52:48 2024 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','a','a','r','c','h','6',
    '4','-','l','i','n','u','x','-','m','u','s','l','-','g','c','c',
    ' ','-','f','P','I','C',' ',' ','-','n','o','s','t','d','i','n',
    'c',' ','-','f','n','o','-','b','u','i','l','t','i','n',' ','-',
    'f','f','r','e','e','s','t','a','n','d','i','n','g',' ','-','W',
    'a','l','l',' ','-','I','/','h','o','m','e','/','o','s','l','a',
    'b','/','D','e','s','k','t','o','p','/','r','u','k','o','s','/',
    'u','l','i','b','/','r','u','x','m','u','s','l','/','i','n','s',
    't','a','l','l','/','i','n','c','l','u','d','e',' ','-','O','3',
    ' ','-','W','n','o','-','f','o','r','m','a','t',' ','-','D','O',
    'P','E','N','S','S','L','_','U','S','E','_','N','O','D','E','L',
    'E','T','E',' ','-','D','O','P','E','N','S','S','L','_','P','I',
    'C',' ','-','D','O','P','E','N','S','S','L','_','C','P','U','I',
    'D','_','O','B','J',' ','-','D','O','P','E','N','S','S','L','_',
    'B','N','_','A','S','M','_','M','O','N','T',' ','-','D','S','H',
    'A','1','_','A','S','M',' ','-','D','S','H','A','2','5','6','_',
    'A','S','M',' ','-','D','S','H','A','5','1','2','_','A','S','M',
    ' ','-','D','K','E','C','C','A','K','1','6','0','0','_','A','S',
    'M',' ','-','D','V','P','A','E','S','_','A','S','M',' ','-','D',
    'E','C','P','_','N','I','S','T','Z','2','5','6','_','A','S','M',
    ' ','-','D','P','O','L','Y','1','3','0','5','_','A','S','M',' ',
    '-','D','N','D','E','B','U','G','\0'
};
